name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2.3.5
      - name: JDK 8
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 8
          cache: 'gradle'
          distribution: 'temurin'
      - name: Build
        run: |
          ./gradlew build --stacktrace
      - uses: actions/upload-artifact@v2
        with:
          name: Plugin Jar
          path: build/libs/*.jar
